### ISSUE TITLE
registry 没有 PicoDet

### ISSUE THREAD

**Issue by umie0128** [Bo396543018/Picodet_Pytorch#5]
Traceback (most recent call last):
  File "tools/train.py", line 185, in <module>
    main()
  File "tools/train.py", line 158, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/zijing.wang/.local/lib/python3.6/site-packages/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/zijing.wang/.local/lib/python3.6/site-packages/mmcv/utils/registry.py", line 213, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/zijing.wang/.local/lib/python3.6/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zijing.wang/.local/lib/python3.6/site-packages/mmcv/utils/registry.py", line 46, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'PicoDet is not in the models registry'

**Comment by Bo396543018** [comment]
这个是PYTHONPATH的问题，通常启动训练是用tools下的dist_train.sh脚本进行训练的，里面有配置PYTHONPATH的命令，后面我会完善一下训练和测试的流程介绍

**Comment by wj51** [comment]
KeyError: 'PicoDet is not in the models registry'

**Comment by wj51** [comment]
请问直接使用python train.py 运行的参数配置怎么写

**Comment by Bo396543018** [comment]
> 请问直接使用python train.py 运行的参数配置怎么写

你需要参考dist_train.sh脚本里的PYTHONPATH配置下，一般在mmdetection目录下export PYTHONPATH=./就可以解决上面那个未注册的问题
